ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS snooze_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS reminder_interval INTEGER DEFAULT 30,
ADD COLUMN IF NOT EXISTS snooze_interval INTEGER DEFAULT 15;
