-- Create quotes table
CREATE TABLE IF NOT EXISTS public.quotes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    text TEXT NOT NULL,
    theory TEXT,
    link TEXT,
    order_index INTEGER GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS policies for quotes
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated_all" ON public.quotes;
CREATE POLICY "authenticated_all" ON public.quotes
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Add last_quote_index to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_quote_index INTEGER DEFAULT 0;

-- Seed data for quotes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.quotes LIMIT 1) THEN
    INSERT INTO public.quotes (text, theory, link) VALUES
    ('O combinado não sai caro, mas o que não foi registrado sai caríssimo.', 'Rastreabilidade Operacional.', NULL),
    ('Quem oferece duas opções de pagamento dá ao cliente o poder de escolha, não o peso da obrigação.', 'Arquitetura de Escolha.', NULL),
    ('O primeiro contato informa, o segundo negocia, mas é o follow-up que converte o dinheiro na conta.', 'Funil de Conversão.', 'https://www.neofin.com.br/blog/estrategias-de-follow-up-inteligente-para-cobranca'),
    ('A palavra ''ajuda'' abre mais portas que a palavra ''cobrança''.', 'Gatilho da Reciprocidade.', 'https://www.cobmais.com.br/blog/gatilhos-mentais-para-cobranca/'),
    ('Está difícil falar com o cliente? Mude o canal, mude o horário, mude o texto. Persistência exige estratégia.', 'Omnichannel.', 'https://solides.com.br/blog/follow-up/'),
    ('Ter o histórico de follow-up na tela é ter autoridade na voz: o cliente percebe que você sabe tudo o que foi dito.', 'Gatilho da Autoridade.', NULL),
    ('Escutar o ''porquê'' do atraso é o primeiro passo para o ''como'' ele vai pagar.', 'Escuta Ativa.', 'https://holdbrasil.com.br/o-poder-da-escuta-ativa-como-transformar-conflitos-em-acordos-no-b2b/'),
    ('A urgência deve ser do prazo, nunca da sua voz.', 'Controle Emocional.', 'https://3cplusnow.com/gatilhos-mentais-para-cobranca-aprenda-como-usar/'),
    ('O follow-up é o guardião da palavra dada. Quem acompanha de perto, colhe o compromisso do cliente.', 'Gatilho da Coerência.', NULL),
    ('Um tom de voz firme, mas educado, desarma defesas e constrói pontes.', 'Rapport e Espelhamento.', 'https://www.docusign.com/pt-br/blog/15-tecnicas-de-negociacao-classicas-que-voce-nao-pode-esquecer'),
    ('Prazo sem follow-up vira desculpa. O combinado só vale se for acompanhado.', 'Gatilho da Coerência.', 'https://3cplusnow.com/follow-up-na-cobranca/'),
    ('Lembre-se: o cliente não é a dívida. Ele está em dívida, e isso é passageiro.', 'Separação Pessoa/Problema.', NULL),
    ('A maioria dos acordos morre no silêncio. O follow-up é o que mantém a negociação viva.', 'Persistência Estratégica.', NULL),
    ('Fale mais sobre o benefício da conta em dia do que sobre a dor do corte.', 'Enquadramento Positivo.', NULL),
    ('Não prometa o que não pode cumprir. A credibilidade é o maior patrimônio do nosso setor.', 'Brand Equity.', 'https://blog.assertivasolucoes.com.br/tecnicas-de-negociacao/'),
    ('O silêncio após uma proposta é uma ferramenta poderosa. Deixe o cliente processar a oferta.', 'Pausa Estratégica.', NULL),
    ('Uma ferramenta de follow-up é o seu GPS: ela garante que nenhum acordo se perca nas curvas do dia a dia.', 'Redução de Carga Cognitiva.', NULL),
    ('Negociar não é vencer o cliente, é vencer o problema que impede o pagamento.', 'Negociação Cooperativa.', NULL),
    ('Pequenos acordos hoje evitam grandes inadimplências amanhã.', 'Técnica do ''Pé na Porta''.', NULL),
    ('Dados precisos no sistema são as armas mais afiadas de um bom negociador.', 'Autoridade por Dados.', NULL),
    ('Um ''não'' agora pode ser apenas um ''ainda não consigo nessas condições''.', 'Persistência Consultiva.', NULL),
    ('Use o nome do cliente. É o som mais doce que ele pode ouvir e gera conexão imediata.', 'Validação Psicológica.', NULL),
    ('Evite o ''mas''. Use o ''e''. ''Entendo sua situação E por isso tenho esta proposta''.', 'Linguagem Inclusiva.', NULL),
    ('O foco da cobrança de serviços essenciais é a continuidade do bem-estar do cliente.', 'Valor Agregado.', NULL),
    ('Trate cada ligação como uma nova oportunidade de recuperar um ativo da empresa.', 'Mindset de Receita.', NULL),
    ('Perguntas abertas fazem o cliente revelar a solução que ele mesmo pode cumprir.', 'Método SPIN.', NULL),
    ('Um acordo cumprido vale mais do que dez promessas vazias.', 'Qualidade de Acordo.', NULL),
    ('Agradecer pelo contato, mesmo sem acordo, deixa a porta aberta para a próxima tentativa.', 'Customer Experience (CX).', NULL),
    ('A diferença entre uma promessa esquecida e um boleto pago está na frequência do seu acompanhamento.', 'Efeito de Recência.', NULL),
    ('Automatizar o lembrete de follow-up te dá tempo para o que importa: ser humano e consultivo.', 'Eficiência Operacional.', NULL),
    ('O follow-up bem feito transforma um devedor reativo em um cliente grato pela solução encontrada.', 'Nurturing.', NULL),
    ('Nossa meta silenciosa: reduzir ruído. Menos ida e volta, mais resolução direta.', 'First Contact Resolution (FCR).', NULL);
  END IF;
END $$;
